### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [Pummas/ugc_sprint_1#24]
Здравствуйте, отличная работа ! Отличное исследование с числовыми занчениями и выводом ! Молодцы, что уделили особое внимание тестам ! Есть небольшие рекомендации:

1. [Тут](https://github.com/Pummas/ugc_sprint_1/tree/main/tests) каталог остался пустым :)  [Здесь](https://github.com/Pummas/ugc_sprint_1/tree/main/tools) тоже пока в нем нет ничего полезного, можно пока убрать.
2. [Тут](https://github.com/Pummas/ugc_sprint_1/blob/038b040d87fae9181f2f38d7926b9638e9f1f4bb/ugc/requirements.txt#L1) можно обновить версии библиотек до более свежих (uvicorn 0.20.0 уже есть, fastapi - 0.92.0)
3. [Здесь](https://github.com/Pummas/ugc_sprint_1/blob/038b040d87fae9181f2f38d7926b9638e9f1f4bb/ugc/src/db/film_view_storage.py#L13)   и в похожих местах - лучше использовать `printf-style` форматирование, например вида `logger.debug("some value: %s", value)` тогда у вас не будет происходить вычисление итоговой строки, если уровень логирования INFO например. https://blog.pilosus.org/posts/2020/01/24/python-f-strings-in-logging/
4. [Здесь](https://github.com/Pummas/ugc_sprint_1/blob/038b040d87fae9181f2f38d7926b9638e9f1f4bb/ugc/src/db/film_view_storage.py#L18) можно попробовать обернуть в lru_cache().
5. [Здесь](https://github.com/Pummas/ugc_sprint_1/blob/038b040d87fae9181f2f38d7926b9638e9f1f4bb/ugc/src/db/kafka_producer.py#L16) можно попробовать использовать [send_and_wait](https://aiokafka.readthedocs.io/en/stable/index.html#aiokafkaproducer)
6. Не нашел в репозитории и в docker-compose.yml нет nginx, а ведь он нужен, 10к problem. Давайте добавим nginx.
7. [Тут](https://github.com/Pummas/ugc_sprint_1/blob/038b040d87fae9181f2f38d7926b9638e9f1f4bb/etl/data/node1/users.xml#L22) в реальных условиях не стоит забывать и оставлять дефолтные значения (править не нужно, просто как заметка. Обычно конфигурацией занимается отдельный человек или даже отдел).
8. [Здесь](https://github.com/Pummas/ugc_sprint_1/blob/038b040d87fae9181f2f38d7926b9638e9f1f4bb/etl/src/etl.py#L17) процесс etl бесконечный, но допустим если возникнет исключение в какой то из строк этого метода, ETL завершится и перегрузка в КХ остановится. Давайте это исправим.

**Comment by RomanBorovskiy** [comment]
1. Убрали
2. Обновлено
3. Исправлено
4. Не требуется,  FilmViewStorage синглтон, поэтому возвращает каждый раз один и тот же экземпляр
5. Исправлено, хотя разницы тут:))   send_and_wait() делает future = send(), потом await future
6. Добавлен NGINX
7. Ок (не исправляли)
8. Каждый компонент (extractor, transformer, loader) обрабатывает свои специфичные исключения. Добавили try except для логирования непредвиденных исключений. Контейнер ETL перезапускается после падения (restart: "always")

**Comment by BigDeepBlue** [comment]
@Pummas @RomanBorovskiy @valerycode @s-morichev  Молодцы ! Принято !
